"""
This module defines a base class for SQLAlchemy models with a custom
naming convention and a primary key field.
"""

from sqlalchemy import Column, Integer
from sqlalchemy.orm import declarative_base, declared_attr

from inflection import pluralize


class PreBase:
    """
    A mixin class that provides a custom table naming convention and
    a primary key field 'id'.

    The table name is generated by pluralizing the lowercase class name.
    """

    @declared_attr
    def __tablename__(cls):
        return pluralize(cls.__name__.lower())

    id = Column(Integer, primary_key=True)


#: The declarative base class extended by PreBase.
Base = declarative_base(cls=PreBase)
